/**
 * GENERATED FILE - do not edit by hand.
 *
 * Produced from the migrated database by scripts/generate-schema.ts.
 * The SQL under ./migrations is the source of truth; run
 * `npm run db:generate-schema` after any migration that changes a column.
 *
 * NUMERIC columns are typed as string on purpose - converting money to a JS
 * number loses cents. Use asMoney() from ../client.ts at the point of use.
 */
import { boolean, date, integer, jsonb, numeric, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const appUser = pgTable("app_user", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  fullName: text("full_name").notNull(),
  role: text("role").notNull(),
  passwordHash: text("password_hash"),
  totpSecret: text("totp_secret"),
  active: boolean("active").notNull(),
  department: text("department"),
  manager: text("manager"),
  phone: text("phone"),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  failedLoginAttempts: integer("failed_login_attempts").notNull(),
  lockedUntil: timestamp("locked_until", { withTimezone: true }),
  passwordChangedAt: timestamp("password_changed_at", { withTimezone: true }),
  totpEnrolledAt: timestamp("totp_enrolled_at", { withTimezone: true }),
  totpLastStep: text("totp_last_step"),
});

export type AppUser = typeof appUser.$inferSelect;
export type NewAppUser = typeof appUser.$inferInsert;

export const appointment = pgTable("appointment", {
  id: text("id").primaryKey(),
  crmLeadId: text("crm_lead_id"),
  crmJobId: text("crm_job_id"),
  appointmentRecordId: text("appointment_record_id"),
  customerName: text("customer_name").notNull(),
  contactName: text("contact_name"),
  phone: text("phone"),
  email: text("email"),
  address: text("address"),
  city: text("city"),
  county: text("county"),
  leadCreatedDate: date("lead_created_date"),
  appointmentSetDate: date("appointment_set_date"),
  appointmentDate: date("appointment_date"),
  appointmentTime: text("appointment_time"),
  demoDate: date("demo_date"),
  resetDate: date("reset_date"),
  saleDate: date("sale_date"),
  ownerStatusUpdateDate: date("owner_status_update_date"),
  ownerFollowUpDate: date("owner_follow_up_date"),
  originalAppointmentSetter: text("original_appointment_setter"),
  rehashAppointmentSetter: text("rehash_appointment_setter"),
  originalSalesRep: text("original_sales_rep"),
  rehashSalesRep: text("rehash_sales_rep"),
  marketingSource: text("marketing_source"),
  referralSource: text("referral_source"),
  sourceCategory: text("source_category"),
  campaign: text("campaign"),
  product: text("product"),
  businessDivision: text("business_division"),
  trade: text("trade"),
  title: text("title"),
  appointmentStatus: text("appointment_status").notNull(),
  debriefStatus: text("debrief_status").notNull(),
  isSalesAppointment: boolean("is_sales_appointment").notNull(),
  exclusionReason: text("exclusion_reason"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  createdBy: text("created_by").notNull(),
  identityKey: text("identity_key"),  // generated by PostgreSQL - never write
});

export type Appointment = typeof appointment.$inferSelect;
export type NewAppointment = typeof appointment.$inferInsert;

export const appointmentImportExclusion = pgTable("appointment_import_exclusion", {
  id: text("id").primaryKey(),
  importBatchId: text("import_batch_id"),
  importedAt: timestamp("imported_at", { withTimezone: true }),
  importedBy: text("imported_by"),
  title: text("title"),
  customerName: text("customer_name"),
  crmLeadId: text("crm_lead_id"),
  appointmentDate: date("appointment_date"),
  appointmentTime: text("appointment_time"),
  exclusionReason: text("exclusion_reason"),
  rowType: text("row_type").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export type AppointmentImportExclusion = typeof appointmentImportExclusion.$inferSelect;
export type NewAppointmentImportExclusion = typeof appointmentImportExclusion.$inferInsert;

export const authEvent = pgTable("auth_event", {
  id: text("id").primaryKey(),
  event: text("event").notNull(),
  email: text("email"),
  succeeded: boolean("succeeded").notNull(),
  ip: text("ip"),
  userAgent: text("user_agent"),
  detail: text("detail"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export type AuthEvent = typeof authEvent.$inferSelect;
export type NewAuthEvent = typeof authEvent.$inferInsert;

export const debrief = pgTable("debrief", {
  id: text("id").primaryKey(),
  appointmentId: text("appointment_id"),
  appointmentRecordId: text("appointment_record_id"),
  crmLeadId: text("crm_lead_id"),
  crmJobId: text("crm_job_id"),
  resultSource: text("result_source"),
  submittedBy: text("submitted_by").notNull(),
  customerName: text("customer_name").notNull(),
  phone: text("phone"),
  address: text("address"),
  city: text("city"),
  appointmentDate: date("appointment_date").notNull(),
  salesRep: text("sales_rep").notNull(),
  secondarySalesRep: text("secondary_sales_rep"),
  primaryRepSplitPct: numeric("primary_rep_split_pct", { precision: 5, scale: 2 }),
  secondaryRepSplitPct: numeric("secondary_rep_split_pct", { precision: 5, scale: 2 }),
  appointmentSetter: text("appointment_setter").notNull(),
  product: text("product"),
  businessDivision: text("business_division"),
  trade: text("trade"),
  appointmentType: text("appointment_type"),
  appointmentOutcome: text("appointment_outcome").notNull(),
  decisionMakerStatus: text("decision_maker_status"),
  oneLegReason: text("one_leg_reason"),
  productsDiscussed: text("products_discussed"),
  productsPresentedOther: text("products_presented_other"),
  firstPriceGiven: numeric("first_price_given", { precision: 12, scale: 2 }),
  price2Given: numeric("price_2_given", { precision: 12, scale: 2 }),
  price3Given: numeric("price_3_given", { precision: 12, scale: 2 }),
  additionalPricesGiven: text("additional_prices_given"),
  pricesGiven: integer("prices_given"),
  financingOffered: boolean("financing_offered"),
  financingNotOfferedReason: text("financing_not_offered_reason"),
  financingOptionPresented: text("financing_option_presented"),
  financingResult: text("financing_result"),
  saleAmount: numeric("sale_amount", { precision: 12, scale: 2 }),
  saleCloseType: text("sale_close_type"),
  salePriceNumber: text("sale_price_number"),
  creditDecline: boolean("credit_decline"),
  cancellation: boolean("cancellation"),
  mainObjection: text("main_objection"),
  objectionCustomerWording: text("objection_customer_wording"),
  preCloseAnswer: text("pre_close_answer"),
  closingQuestionAnswer: text("closing_question_answer"),
  step7Result: text("step7_result"),
  walkOfLifeIssues: text("walk_of_life_issues"),
  step7CoachingNotes: text("step7_coaching_notes"),
  step7CoachingFollowup: text("step7_coaching_followup"),
  step7ThingsToReview: text("step7_things_to_review"),
  repResponse: text("rep_response"),
  clientResponse1: text("client_response_1"),
  repResponse2: text("rep_response_2"),
  clientResponse2: text("client_response_2"),
  repResponse3: text("rep_response_3"),
  cancellationReason: text("cancellation_reason"),
  resetNeeded: boolean("reset_needed"),
  resetStatus: text("reset_status"),
  resetDate: date("reset_date"),
  resetReason: text("reset_reason"),
  resetAppointmentScheduled: boolean("reset_appointment_scheduled"),
  resetFollowUpNotes: text("reset_follow_up_notes"),
  followUpNeeded: boolean("follow_up_needed"),
  followUpBucket: text("follow_up_bucket"),
  followUpDate: date("follow_up_date"),
  estimateSentDate: timestamp("estimate_sent_date", { withTimezone: true }),
  saleDate: date("sale_date"),
  saleSignedDate: date("sale_signed_date"),
  leadReferralDate: date("lead_referral_date"),
  notes: text("notes"),
  marketingSource: text("marketing_source"),
  referralSource: text("referral_source"),
  selfGenSource: text("self_gen_source"),
  salesAppointment: text("sales_appointment"),
  nonSalesReason: text("non_sales_reason"),
  historicalReview: text("historical_review"),
  matched: boolean("matched").notNull(),
  dataQualityFlag: text("data_quality_flag"),
  managerReviewNeeded: boolean("manager_review_needed").notNull(),
  contingencySigned: boolean("contingency_signed"),
  contingencySignedDate: date("contingency_signed_date"),
  demoCompleted: boolean("demo_completed"),
  insuranceOutcome: text("insurance_outcome"),
  upgradePrice1: numeric("upgrade_price_1", { precision: 12, scale: 2 }),
  upgradePrice2: numeric("upgrade_price_2", { precision: 12, scale: 2 }),
  upgradePrice3: numeric("upgrade_price_3", { precision: 12, scale: 2 }),
  otherPricesGiven: boolean("other_prices_given"),
  otherPricesDetails: text("other_prices_details"),
  otherPricesAmount: numeric("other_prices_amount", { precision: 12, scale: 2 }),
  totalJobPriceProvided: boolean("total_job_price_provided"),
  totalJobPrice: numeric("total_job_price", { precision: 12, scale: 2 }),
  upgradeSoldAccepted: boolean("upgrade_sold_accepted"),
  acceptedUpgradeAmount: numeric("accepted_upgrade_amount", { precision: 12, scale: 2 }),
  finalContractSigned: boolean("final_contract_signed"),
  finalContractDate: date("final_contract_date"),
  lastEditedAt: timestamp("last_edited_at", { withTimezone: true }),
  lastEditedBy: text("last_edited_by"),
  editReason: text("edit_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  createdBy: text("created_by").notNull(),
});

export type Debrief = typeof debrief.$inferSelect;
export type NewDebrief = typeof debrief.$inferInsert;

export const jpAppointment = pgTable("jp_appointment", {
  id: text("id").primaryKey(),
  jpAppointmentId: text("jp_appointment_id").notNull(),
  title: text("title"),
  appointmentDate: date("appointment_date"),
  appointmentTime: text("appointment_time"),
  customerName: text("customer_name"),
  location: text("location"),
  crmLeadId: text("crm_lead_id"),
  crmJobId: text("crm_job_id"),
  salesRep: text("sales_rep"),
  appointmentSetter: text("appointment_setter"),
  division: text("division"),
  isSalesType: boolean("is_sales_type").notNull(),
  isInsurance: boolean("is_insurance").notNull(),
  hasResult: boolean("has_result").notNull(),
  resultGroup: text("result_group"),
  resultOptionName: text("result_option_name"),
  twoLegAnswer: text("two_leg_answer"),
  twoLegRaw: text("two_leg_raw"),
  jpCreatedAt: timestamp("jp_created_at", { withTimezone: true }),
  jpUpdatedAt: timestamp("jp_updated_at", { withTimezone: true }),
  raw: jsonb("raw").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export type JpAppointment = typeof jpAppointment.$inferSelect;
export type NewJpAppointment = typeof jpAppointment.$inferInsert;

export const jpJob = pgTable("jp_job", {
  id: text("id").primaryKey(),
  jpJobId: text("jp_job_id").notNull(),
  jobNumber: text("job_number"),
  jobName: text("job_name"),
  division: text("division"),
  trades: text("trades"),
  isInsurance: boolean("is_insurance").notNull(),
  currentStage: text("current_stage"),
  contractSignedDate: date("contract_signed_date"),
  jpCreatedAt: timestamp("jp_created_at", { withTimezone: true }),
  jpUpdatedAt: timestamp("jp_updated_at", { withTimezone: true }),
  totalJobRevenue: numeric("total_job_revenue", { precision: 12, scale: 2 }),
  totalJobPrice: numeric("total_job_price", { precision: 12, scale: 2 }),
  totalChangeOrderAmount: numeric("total_change_order_amount", { precision: 12, scale: 2 }),
  financialsFetchedAt: timestamp("financials_fetched_at", { withTimezone: true }),
  raw: jsonb("raw").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export type JpJob = typeof jpJob.$inferSelect;
export type NewJpJob = typeof jpJob.$inferInsert;

export const listOption = pgTable("list_option", {
  id: text("id").primaryKey(),
  category: text("category").notNull(),
  value: text("value").notNull(),
  active: boolean("active").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  createdBy: text("created_by").notNull(),
});

export type ListOption = typeof listOption.$inferSelect;
export type NewListOption = typeof listOption.$inferInsert;

export const marketingSource = pgTable("marketing_source", {
  id: text("id").primaryKey(),
  rawSource: text("raw_source"),
  standardSource: text("standard_source").notNull(),
  sourceCategory: text("source_category"),
  campaign: text("campaign"),
  active: boolean("active").notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  createdBy: text("created_by").notNull(),
});

export type MarketingSource = typeof marketingSource.$inferSelect;
export type NewMarketingSource = typeof marketingSource.$inferInsert;

export const session = pgTable("session", {
  tokenHash: text("token_hash").primaryKey(),
  userId: text("user_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  absoluteExpiresAt: timestamp("absolute_expires_at", { withTimezone: true }).notNull(),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  csrfTokenHash: text("csrf_token_hash").notNull(),
  ip: text("ip"),
  userAgent: text("user_agent"),
});

export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;

export const syncConflict = pgTable("sync_conflict", {
  id: text("id").primaryKey(),
  syncRunId: text("sync_run_id"),
  category: text("category").notNull(),
  reason: text("reason").notNull(),
  appointmentRecordId: text("appointment_record_id"),
  crmLeadId: text("crm_lead_id"),
  crmJobId: text("crm_job_id"),
  resolutionStatus: text("resolution_status").notNull(),
  details: text("details"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export type SyncConflict = typeof syncConflict.$inferSelect;
export type NewSyncConflict = typeof syncConflict.$inferInsert;

export const syncRun = pgTable("sync_run", {
  id: text("id").primaryKey(),
  mode: text("mode").notNull(),
  status: text("status").notNull(),
  dateFrom: date("date_from").notNull(),
  dateTo: date("date_to").notNull(),
  incrementalSince: timestamp("incremental_since", { withTimezone: true }),
  fullBackfill: boolean("full_backfill").notNull(),
  checkpoint: text("checkpoint"),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  startedBy: text("started_by"),
  counts: jsonb("counts").notNull(),
  errorCodes: text("error_codes").array().notNull(),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export type SyncRun = typeof syncRun.$inferSelect;
export type NewSyncRun = typeof syncRun.$inferInsert;

export const uploadedFile = pgTable("uploaded_file", {
  id: text("id").primaryKey(),
  storageKey: text("storage_key").notNull(),
  originalName: text("original_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: text("size_bytes").notNull(),
  checksum: text("checksum").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
});

export type UploadedFile = typeof uploadedFile.$inferSelect;
export type NewUploadedFile = typeof uploadedFile.$inferInsert;
