/**
 * Generates src/db/schema/index.ts from the live, migrated database.
 *
 * The SQL migrations are the single source of truth for the schema; these types
 * are derived from them, never the other way round. Regenerating after a
 * migration means the compiler finds every caller a column change affects.
 *
 *   DATABASE_URL=... npm run db:generate-schema
 *
 * Written in-repo rather than using `drizzle-kit pull` because drizzle-kit's
 * dependency check does not resolve drizzle-orm through this npm-workspaces
 * layout. This is ~100 lines, deterministic, and has no such problem.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/db/schema/index.ts");

interface Col {
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: "YES" | "NO";
  column_default: string | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
  is_generated: "ALWAYS" | "NEVER";
  is_identity: string;
}

const camel = (s: string) => s.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const pascal = (s: string) => { const c = camel(s); return c.charAt(0).toUpperCase() + c.slice(1); };

function drizzleType(c: Col): { call: string; imports: string[] } {
  const n = `"${c.column_name}"`;
  switch (c.udt_name) {
    case "text":
    case "varchar":
      return { call: `text(${n})`, imports: ["text"] };
    case "bool":
      return { call: `boolean(${n})`, imports: ["boolean"] };
    case "int4":
      return { call: `integer(${n})`, imports: ["integer"] };
    case "date":
      return { call: `date(${n})`, imports: ["date"] };
    case "timestamptz":
      return { call: `timestamp(${n}, { withTimezone: true })`, imports: ["timestamp"] };
    case "jsonb":
      return { call: `jsonb(${n})`, imports: ["jsonb"] };
    case "numeric":
      // Kept as string end-to-end: numeric -> JS number loses cents, and these
      // columns hold money. Convert explicitly with asMoney() where needed.
      return {
        call: `numeric(${n}, { precision: ${c.numeric_precision ?? 12}, scale: ${c.numeric_scale ?? 2} })`,
        imports: ["numeric"],
      };
    case "_text":
      return { call: `text(${n}).array()`, imports: ["text"] };
    default:
      return { call: `text(${n})`, imports: ["text"] };
  }
}

const main = async () => {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  const pool = new pg.Pool({ connectionString: url, max: 1 });

  const { rows: cols } = await pool.query<Col>(`
    SELECT c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable,
           c.column_default, c.numeric_precision, c.numeric_scale,
           c.is_generated, c.is_identity
      FROM information_schema.columns c
      JOIN information_schema.tables t
        ON t.table_name = c.table_name AND t.table_schema = c.table_schema
     WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
       AND c.table_name <> 'schema_migrations'
     ORDER BY c.table_name, c.ordinal_position`);

  const { rows: pks } = await pool.query<{ table_name: string; column_name: string }>(`
    SELECT tc.table_name, kcu.column_name
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema
     WHERE tc.table_schema = 'public' AND tc.constraint_type = 'PRIMARY KEY'`);
  await pool.end();

  const pkOf = new Map(pks.map((p) => [p.table_name, p.column_name]));
  const byTable = new Map<string, Col[]>();
  for (const c of cols) {
    if (!byTable.has(c.table_name)) byTable.set(c.table_name, []);
    byTable.get(c.table_name)!.push(c);
  }

  const imports = new Set<string>(["pgTable"]);
  const blocks: string[] = [];

  for (const [table, columns] of [...byTable].sort()) {
    const lines: string[] = [];
    for (const c of columns) {
      const { call, imports: need } = drizzleType(c);
      need.forEach((i) => imports.add(i));
      let expr = call;
      if (pkOf.get(table) === c.column_name) expr += ".primaryKey()";
      else if (c.is_nullable === "NO") expr += ".notNull()";
      // A GENERATED ALWAYS column is computed by PostgreSQL and must never be
      // written by the application; surfaced read-only via $type + a comment.
      const note = c.is_generated === "ALWAYS" ? "  // generated by PostgreSQL - never write" : "";
      lines.push(`  ${camel(c.column_name)}: ${expr},${note}`);
    }
    blocks.push(
      `export const ${camel(table)} = pgTable("${table}", {\n${lines.join("\n")}\n});\n\n` +
        `export type ${pascal(table)} = typeof ${camel(table)}.$inferSelect;\n` +
        `export type New${pascal(table)} = typeof ${camel(table)}.$inferInsert;`,
    );
  }

  const header = `/**
 * GENERATED FILE - do not edit by hand.
 *
 * Produced from the migrated database by scripts/generate-schema.ts.
 * The SQL under ./migrations is the source of truth; run
 * \`npm run db:generate-schema\` after any migration that changes a column.
 *
 * NUMERIC columns are typed as string on purpose - converting money to a JS
 * number loses cents. Use asMoney() from ../client.ts at the point of use.
 */
import { ${[...imports].sort().join(", ")} } from "drizzle-orm/pg-core";

`;
  writeFileSync(OUT, header + blocks.join("\n\n") + "\n", "utf8");
  console.log(`wrote ${OUT}`);
  console.log(`  ${byTable.size} tables, ${cols.length} columns`);
};

await main();
